
mongodb_host: "mongodb-{{ env }}.kriiishmatic.fun"
redis_host: "redis-{{ env }}.kriiishmatic.fun"
catalogue_host: "catalogue-{{ env }}.kriiishmatic.fun"
rabbitmq_host: "rabbitmq-{{ env }}.kriiishmatic.fun"
mysql_host: "mysql-{{ env }}.kriiishmatic.fun"
cart_host: "cart-{{ env }}.kriiishmatic.fun"
user_host: "user-{{ env }}.kriiishmatic.fun"
shipping_host: "shipping-{{ env }}.kriiishmatic.fun"
payment_host: "payment-{{ env }}.kriiishmatic.fun"
frontend_host: "frontend-{{ env }}.kriiishmatic.fun"

ansible_user: ec2-user
ansible_password: DevOps321
