 - name: Installing mysql
   ansible.builtin.package:
    name: mysql-server
    state: present
  
 - name: install mysql python libraries
   ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
      loop:
      - botocore
      - boto3
      
 - name: Staring service
   ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes
     
 - name: Id roboshop with password
   ansible.builtin.command: mysql_secure_installation --set-root-pass {{MYSQL_ROOT_PASSWORD}}