 - name: Installing mysql
   ansible.builtin.package:
    name: mysql-server
    state: present
  
 - name: Ensure boto3 and botocore are installed
   ansible.builtin.pip:
      name:
        - boto3
        - botocore
      state: present
      executable: pip3

 - name: Copying mysql repo
 - name: Staring service
   ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes
     
 - name: Id roboshop with password
   ansible.builtin.command: mysql_secure_installation --set-root-pass {{MYSQL_ROOT_PASSWORD}}